language: go
sudo: false

matrix:
  include:
    - go: 1.6
    - go: tip
script:
  - go get ./...
  - go build ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet $(go list ./... | grep -v /vendor/)
