language: go
sudo: false

matrix:
  include:
    - go: 1.8
    - go: tip
install:
  - go get -u github.com/golang/dep/cmd/dep
script:
  - dep ensure -v
  - go get ./...
  - go build ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet $(go list ./... | grep -v /vendor/)
